---
#configmap (person-service) example
apiVersion: v1
kind: ConfigMap
metadata:
  name: person-service
  #namespace: default
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,dev,xyz"
  hello.message: "Hello from person-service in Kubernetes!"
  #another way will be to use the application.yaml to map config values to env variables
  person-service.yml: |
    greeting:
      message: "Hello from person-service configmap in Kubernetes!"
  person-service-dev.yml: |
    greeting:
      message: "Hello from person-service configmap in Kubernetes!. this is a dev profile"
---
## configmap (address-service) example
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-service
  #namespace: default
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,dev,xyz"
  hello.message: "Hello from address-service in Kubernetes!"
  #another way will be to use the application.yaml to map config values to env variables
  address-service.yml: |
    greeting:
      message: "Hello from address-service configmap in Kubernetes!"
---
#secret (person-service) example
apiVersion: v1
kind: Secret
metadata:
  name: person-service
  labels:
    app: person-service
type: Opaque
data:
  # create bas64 encoded values. e.g. echo -n 'my-secret-password' | base64
  trocks.apiKey: "YjcwaXVuYVRZRmJ2OSM="
  db.password: "TWlja1lNMHVfMw=="
  db.username: "dHJvY2tz"
---
#secret (address-service) example
apiVersion: v1
kind: Secret
metadata:
  name: address-service
  labels:
    app: address-service
type: Opaque
data:
  # create bas64 encoded values. e.g. echo -n 'my-secret-password' | base64
  trocks.apiKey: "VDBPdGhQX3N0MzJvMjU="
  db.password: "VDBPdGhKX3N0MzJvNjU="
  db.username: "dHJvY2tz"
