spring.application.name: address-service
server:
  port: 8080
---
#kubernets profile
spring:
   config.activate.on-profile: kubernetes
---
#docker-compose profile
spring:
   config.activate.on-profile: docker
---
#local profile
spring:
   config.activate.on-profile: local
server:
  port: 8082