apiVersion: v1
name: spring-boot-services
description: Application services
type: application
version: 1.0.0 #chart version
appVersion: 1.0.0
keywords:
  - springboot
  - springcloud
  - gateway
  - person
  - address