ingress:
  enabled: false
spring:
  profiles:
    active: dev,kubernetes
namespace: terraform-trocks-namespace
app:
  name: generic-service
dockerImage: generic-service:latest
apps:
  gateway-service:
    name: gateway-service
    image:
      repository: 194205500841.dkr.ecr.us-east-2.amazonaws.com/gateway-service
      tag: "1e7a8de"
    replicas: 1
    discovery:
      enabled: false
  person-service:
    name: person-service
    image:
      repository: 194205500841.dkr.ecr.us-east-2.amazonaws.com/person-service
      tag: "2541c1a"
    replicas: 2
    discovery:
      enabled: true
  # address-service:
  #   name: address-service
  # config-service:
  #   name: config-service
