apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  #namespace: trocks-api
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  # ingressClassName: nginx #for NGINX Ingress Controller (minikube)
  ingressClassName: alb #for AWS ALB Ingress Controller
  rules:
    # - host: api.localhost #uncomment and set this only if using host-based routing
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # name: gateway-service 
                name: {{ .Values.app.name }} #fetching the app name from Values.yaml
                port:
                  number: 80 #service port defined in service-gateway-service.yml